version: "3.7"

services:
  db1:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase4
      POSTGRES_USER: user4
      POSTGRES_PASSWORD: password4
    ports:
      - "5435:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
      - ./postgres-init/01-create_post_schema.sh:/docker-entrypoint-initdb.d/01-create_post_schema.sh
      - ./postgres-init/02-create_role.sh:/docker-entrypoint-initdb.d/02-create_role.sh

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  db1_data:
